### ISSUE TITLE
5.3.

### ISSUE THREAD

**Issue by lsiedlaczek** [tomkoski/Eloquent-JS#12]
. linie 11-17 i 42/48 mozna skrocic (zobacz ktore elementy sie powtarzaja i czy tak to musi wygladac?
. linia 28 jest dla mnie kompletnie nieczytelna. nigdy nie zapisuj ajko jednolinijkowca takich rzeczy, poza tym nie ma czegos takiego jak return(sth), w ten sposob robisz return (sth) co rownie dobrze mozesz zapisac po prostu jako return sth

. srednik w linii 63 jest totalnie z dupy

**Comment by tomkoski** [comment]
-usunalem powtarzajace sie elementy
-zmienilem zapis callbacka. prosze, daj znac czy teraz jest ok.
-zmienilem return
-usunalem srednik

**Comment by lsiedlaczek** [comment]
jest okejka.
tam sa problemy z wcieciami ale juz nie bawmy sie w detale. uwazaj na to nastepnym razem.

**Comment by tomkoski** [comment]
dzieki, poprawilem pare wciec, mam nadzieje, ze jest juz lepiej.
