### ISSUE TITLE
6-3

### ISSUE THREAD

**Issue by lsiedlaczek** [tomkoski/Eloquent-JS#14]
1. wstawiaj prosze nawiasy przy warunku w ternary
```javascript
var sth = val2 >= val1+5 ? val1+5 : val2;
// czy:
var sth = (val2 >= val1+5) ? val1+5 : val2;
```
co dla Ciebie jest czytelniejsze?

2. popelniasz blad logiczny, bo uzalezniasz logike RangeSeq i ArraySeq od logFive (wrzucasz tam w srodek magiczna liczbe 5). czy potrafisz zrobic to tak, zeby nie umieszczac w srodku zadnych magicznych liczb? + dodatkowo napisz funkcje log(object, count), ktora bedzie logowac Ci count liczb z objektu podanego jako pierwszy parametr.
w mysl tych zalozen: logFive(sth) === log(sth, 5);

problem z 
```javascript
do {
  // something
} while (conditions)
```
jest taki, ze wykona sie zawsze PRZYNAJMNIEJ jeden raz (bo warunki sprawdzane sa PO kazdorazowym wykonaniu petli), dlatego staramy sie unikac tej petli zapisywanej w taki sposob i zamieniamy to na:
```javascript
while (conditions) {
  // something
}


ps. 6.1 i 6.2 sa ok, tylko wciecia do poprawy

**Comment by tomkoski** [comment]
poprawilem wciecia i ternary. zmienilem funkcje log.

**Comment by lsiedlaczek** [comment]
next() powinno dzialac nawet jesli nie podasz parametru.
arraySeq.next(i) nie powinno wybierac elementu nr i z tablicy tylko powiekszac licznik elementow o i i wybierac te pozycje
